
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
    "tutorials": [
        "innovation-studio-tutorials/index",
        "innovation-studio-tutorials/create-business-entity-with-several-attributes",
        "innovation-studio-tutorials/create-onetomany-relationships",
        "innovation-studio-tutorials/create-a-form-driven-flow"
    ],
    "docs": [
        "innovation-studio-developer/intro",
        {
            "type": "category",
            "label": "Evolutive Data Core",
            "items": [
                "innovation-studio-developer/evolutive-data-core",
                "innovation-studio-developer/data-model-designer",
                "innovation-studio-developer/data-model-explorer",
                "innovation-studio-developer/data-import-templates",
                "innovation-studio-developer/data-governance",
                "innovation-studio-developer/data-pipes"
            ]
        },
        {
            "type": "category",
            "label": "Digital Experience",
            "items": [
                "innovation-studio-developer/digital-experience",
                {
                    "type": "category",
                    "label": "Customer Journeys",
                    "items": [
                        "innovation-studio-developer/digital-journeys",
                        "innovation-studio-developer/form-driven-flows",
                        "innovation-studio-developer/custom-flows",
                        "innovation-studio-developer/digital-flow-processing",
                        "innovation-studio-developer/custom-ui",
                        "innovation-studio-developer/code-execution-sequence",
                        "innovation-studio-developer/digital-journey-context",
                        {
                            "type": "category",
                            "label": "UI Designer",
                            "items": [
                                "innovation-studio-developer/ui-designer",
                                "innovation-studio-developer/define-the-form-layout",
                                "innovation-studio-developer/add-attributes",
                                "innovation-studio-developer/configure-and-add-relations",
                                "innovation-studio-developer/work-with-buttons",
                                "innovation-studio-developer/access-predefined-html-templates",
                                "innovation-studio-developer/add-entity-extension-child-collection-support"
                            ]
                        },
                        "innovation-studio-developer/built-in-analytics",
                        "innovation-studio-developer/code-snippets-support"
                    ]
                },
                {
                    "type": "category",
                    "label": "Digital FrontEnds",
                    "items": [
                        "innovation-studio-developer/dashboards",
                        "innovation-studio-developer/widgets",
                        "innovation-studio-developer/menu-items",
                        "innovation-studio-developer/custom-themes",
                        "innovation-studio-developer/portal-profiles",
                        "innovation-studio-developer/anonymous-frontends",
                        "innovation-studio-developer/digital-experience-portals"
                    ]
                }
            ]
        },
        "innovation-studio-developer/automation-blocks",
        "innovation-studio-developer/hyper-personalization-automation",
        "innovation-studio-developer/app-data-forms"
    ]
}
/*
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  */

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
};
*/

module.exports = sidebars;
